services:
  app:
    build: .
    container_name: contacts-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: contacts-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
